import "../dist/data-observer"

test("词法分析", () => {
    var nodeList = vm.Interpreter.toWords("a +  b - c")
    expect(nodeList[0].type).toEqual(vm.NodeType.word)
    expect(nodeList[0].value).toEqual("a")
    expect(nodeList[1].type).toEqual(vm.NodeType["+"])
    expect(nodeList[1].value).toEqual(null)
    expect(nodeList[2].type).toEqual(vm.NodeType.word)
    expect(nodeList[2].value).toEqual("b")
    expect(nodeList[3].type).toEqual(vm.NodeType["-"])
    expect(nodeList[3].value).toEqual(null)
    expect(nodeList[4].type).toEqual(vm.NodeType.word)
    expect(nodeList[4].value).toEqual("c")


    var nodeList = vm.Interpreter.toWords("a.b.c")
    expect(nodeList[0].type).toEqual(vm.NodeType.word)
    expect(nodeList[0].value).toEqual("a")
    expect(nodeList[1].type).toEqual(vm.NodeType["."])
    expect(nodeList[1].value).toEqual(null)
    expect(nodeList[2].type).toEqual(vm.NodeType.word)
    expect(nodeList[2].value).toEqual("b")
    expect(nodeList[3].type).toEqual(vm.NodeType["."])
    expect(nodeList[3].value).toEqual(null)
    expect(nodeList[4].type).toEqual(vm.NodeType.word)
    expect(nodeList[4].value).toEqual("c")

    var nodeList = vm.Interpreter.toWords("aa>=b")
    expect(nodeList[0].type).toEqual(vm.NodeType.word)
    expect(nodeList[0].value).toEqual("aa")
    expect(nodeList[1].type).toEqual(vm.NodeType[">="])
    expect(nodeList[1].value).toEqual(null)
    expect(nodeList[2].type).toEqual(vm.NodeType.word)
    expect(nodeList[2].value).toEqual("b")

    var nodeList = vm.Interpreter.toWords("(a+b-c)*d/e**4>123<312>=11.1<=222!=3==4&&'aa'||\"bb\"!`cc`,")
    expect(nodeList[0].type).toEqual(vm.NodeType["("])
    expect(nodeList[0].value).toEqual(null)
    expect(nodeList[1].type).toEqual(vm.NodeType.word)
    expect(nodeList[1].value).toEqual("a")
    expect(nodeList[2].type).toEqual(vm.NodeType["+"])
    expect(nodeList[2].value).toEqual(null)
    expect(nodeList[3].type).toEqual(vm.NodeType.word)
    expect(nodeList[3].value).toEqual("b")
    expect(nodeList[4].type).toEqual(vm.NodeType["-"])
    expect(nodeList[4].value).toEqual(null)
    expect(nodeList[5].type).toEqual(vm.NodeType.word)
    expect(nodeList[5].value).toEqual("c")
    expect(nodeList[6].type).toEqual(vm.NodeType[")"])
    expect(nodeList[6].value).toEqual(null)
    expect(nodeList[7].type).toEqual(vm.NodeType["*"])
    expect(nodeList[7].value).toEqual(null)
    expect(nodeList[8].type).toEqual(vm.NodeType.word)
    expect(nodeList[8].value).toEqual("d")
    expect(nodeList[9].type).toEqual(vm.NodeType["/"])
    expect(nodeList[9].value).toEqual(null)
    expect(nodeList[10].type).toEqual(vm.NodeType.word)
    expect(nodeList[10].value).toEqual("e")
    expect(nodeList[11].type).toEqual(vm.NodeType["**"])
    expect(nodeList[11].value).toEqual(null)
    expect(nodeList[12].type).toEqual(vm.NodeType.number)
    expect(nodeList[12].value).toEqual(4)
    expect(nodeList[13].type).toEqual(vm.NodeType[">"])
    expect(nodeList[13].value).toEqual(null)
    expect(nodeList[14].type).toEqual(vm.NodeType.number)
    expect(nodeList[14].value).toEqual(123)
    expect(nodeList[15].type).toEqual(vm.NodeType["<"])
    expect(nodeList[15].value).toEqual(null)
    expect(nodeList[16].type).toEqual(vm.NodeType.number)
    expect(nodeList[16].value).toEqual(312)
    expect(nodeList[17].type).toEqual(vm.NodeType[">="])
    expect(nodeList[17].value).toEqual(null)
    expect(nodeList[18].type).toEqual(vm.NodeType.number)
    expect(nodeList[18].value).toEqual(11.1)
    expect(nodeList[19].type).toEqual(vm.NodeType["<="])
    expect(nodeList[19].value).toEqual(null)
    expect(nodeList[20].type).toEqual(vm.NodeType.number)
    expect(nodeList[20].value).toEqual(222)
    expect(nodeList[21].type).toEqual(vm.NodeType["!="])
    expect(nodeList[21].value).toEqual(null)
    expect(nodeList[22].type).toEqual(vm.NodeType.number)
    expect(nodeList[22].value).toEqual(3)
    expect(nodeList[23].type).toEqual(vm.NodeType["=="])
    expect(nodeList[23].value).toEqual(null)
    expect(nodeList[24].type).toEqual(vm.NodeType.number)
    expect(nodeList[24].value).toEqual(4)
    expect(nodeList[25].type).toEqual(vm.NodeType["&&"])
    expect(nodeList[25].value).toEqual(null)
    expect(nodeList[26].type).toEqual(vm.NodeType.string)
    expect(nodeList[26].value).toEqual("aa")
    expect(nodeList[27].type).toEqual(vm.NodeType["||"])
    expect(nodeList[27].value).toEqual(null)
    expect(nodeList[28].type).toEqual(vm.NodeType.string)
    expect(nodeList[28].value).toEqual("bb")
    expect(nodeList[29].type).toEqual(vm.NodeType["!"])
    expect(nodeList[29].value).toEqual(null)
    expect(nodeList[30].type).toEqual(vm.NodeType.string)
    expect(nodeList[30].value).toEqual("cc")
    expect(nodeList[31].type).toEqual(vm.NodeType[","])
    expect(nodeList[31].value).toEqual(null)


})